using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Mlang.Model;

namespace Mlang.Language;

internal abstract class GLSLOutputVisitor : MlangOutputVisitor
{
    protected const string TransferredInstancePrefix = "instance_";

    protected readonly ASTStageBlock stageBlock;
    protected readonly PipelineState pipeline;
    protected readonly IOptionValueSet optionValues;
    protected readonly ISet<ASTDeclaration> transferredInstanceVars;
    protected bool IsInstanced => optionValues.GetBool(Compiler.IsInstancedOptionName);

    protected GLSLOutputVisitor(
        ASTStageBlock stageBlock,
        PipelineState pipeline,
        IOptionValueSet optionValues,
        ISet<ASTDeclaration> transferredInstanceVars,
        TextWriter outputWriter)
        : base(new CodeWriter(outputWriter, disposeWriter: false))
    {
        this.stageBlock = stageBlock;
        this.pipeline = pipeline;
        this.optionValues = optionValues;
        this.transferredInstanceVars = transferredInstanceVars;
    }

    public override bool Visit(ASTNode node) => node switch
    {
        ASTNumericType numeric => Write(numeric),
        ASTArrayType array => Write(array),
        ASTBufferType buffer => Write(buffer),

        _ => base.Visit(node)
    };

    protected void WritePreamble()
    {
        Writer.WriteLine("#version 450");
        Writer.WriteLine($"// This file was generated by Mlang {typeof(Compiler).Assembly.GetName().Version}");
        Writer.WriteLine();
    }

    protected void WriteApplicableStorageBlocks(ASTTranslationUnit unit)
    {
        foreach (var block in unit.Blocks.OfType<ASTStorageBlock>().Where(b => b.EvaluateCondition(optionValues)))
            block.Visit(this);
    }

    protected void WriteFunctions(ASTTranslationUnit unit)
    {
        foreach (var function in unit.Blocks.OfType<ASTFunction>().Concat(stageBlock.Functions))
            function.Visit(this);
    }

    protected void WriteStorageBlock(ASTStorageBlock block, string prefix)
    {
        foreach (var decl in block.Declarations)
            WriteDeclaration(decl, prefix, asStatement: true);
        Writer.WriteLine();
    }

    protected void WriteInstanceVarying(ASTStorageBlock block, string prefix)
    {
        foreach (var decl in block.Declarations.Where(transferredInstanceVars.Contains))
            WriteDeclaration(decl, prefix, asStatement: true, TransferredInstancePrefix);
        Writer.WriteLine();
    }

    protected void WriteUniformBlock(ASTStorageBlock block)
    {
        foreach (var decl in block.Declarations.Where(d => d.Type.IsBindingType))
            WriteDeclaration(decl, "uniform", asStatement: true);
        var nonBindings = block.Declarations.Where(d => !d.Type.IsBindingType);
        if (nonBindings.Any())
        {
            Writer.Write("uniform block_");
            Writer.Write(block.Range.Start.Line);
            Writer.Write('_');
            Writer.Write(block.Range.Start.Column);
            Writer.WriteLine(" {");
            PushIndent();
            foreach (var decl in nonBindings)
                WriteDeclaration(decl, prefix: "", asStatement: true);
            PopIndent();
            Writer.WriteLine("};");
        }
        Writer.WriteLine();
    }

    private void WriteDeclaration(ASTDeclaration declaration, string prefix, bool asStatement, string? namePrefix = null)
    {
        var mlangVisitor = new MlangOutputVisitor(Writer);
        if (!string.IsNullOrWhiteSpace(prefix))
        {
            Writer.Write(prefix);
            Writer.Write(' ');
        }
        declaration.Type.Visit(this);
        Writer.Write(' ');
        if (namePrefix != null)
            Writer.Write(namePrefix);
        Writer.Write(declaration.Name);
        if (declaration.Type is ASTArrayType array)
        {
            Writer.Write('[');
            array.Size?.Visit(mlangVisitor);
            Writer.Write(']');
        }
        if (declaration.Type is ASTBufferType)
            Writer.Write("; }");
        if (declaration.Initializer != null)
        {
            Writer.Write(" = ");
            declaration.Initializer.Visit(mlangVisitor);
        }
        if (asStatement)
            Writer.WriteLine(';');
    }

    protected void WriteMainFunction(bool withInstanceVarTransfers)
    {
        Writer.WriteLine("void main() {");
        PushIndent();

        if (transferredInstanceVars.Count > 0)
        {
            foreach (var decl in transferredInstanceVars)
            {
                Writer.Write(TransferredInstancePrefix);
                Writer.Write(decl.Name);
                Writer.Write(" = ");
                Writer.Write(decl.Name);
                Writer.WriteLine(";");
            }
            Writer.WriteLine();
        }
        foreach (var stmt in stageBlock.Statements)
            stmt.Visit(this);
        PopIndent();

        Writer.WriteLine("}");
        Writer.WriteLine();
    }

    private bool Write(ASTNumericType type)
    {
        Writer.Write(type.Type.GLSLName); // instead of Mlang, e.g. float3 -> vec3
        return false;
    }

    private bool Write(ASTArrayType array)
    {
        // we have to move the size at the end of each declaration
        array.Element.Visit(this);
        return false;
    }

    private bool Write(ASTBufferType buffer)
    {
        Writer.Write("buffer buffer_");
        Writer.Write(buffer.Range.Start.Line);
        Writer.Write('_');
        Writer.Write(buffer.Range.Start.Column);
        Writer.Write(" { ");
        buffer.Inner.Visit(this);
        return false;
    }
}
